export const CBC_GRADES = [
  "PP1",
  "PP2",
  "Grade 1",
  "Grade 2",
  "Grade 3",
  "Grade 4",
  "Grade 5",
  "Grade 6",
  "Grade 7",
  "Grade 8",
  "Grade 9",
  "Grade 10",
  "Grade 11",
  "Grade 12",
];
export const CBC_SUBJECTS = [
  // Pre-Primary (PP1-PP2)
  "Language Activities",
  "Mathematical Activities",
  "Environmental Activities",
  "Psychomotor and Creative Activities",
  "Religious Education Activities",
  // Lower Primary (Grades 1-3)
  "Kiswahili Language Activities",
  "English Language Activities",
  "Literacy",
  "Indigenous Language Activities",
  "Hygiene and Nutrition Activities",
  "Movement and Creative Activities",
  // Upper Primary (Grades 4-6)
  "English",
  "Kiswahili",
  "Home Science",
  "Agriculture",
  "Science and Technology",
  "Mathematics",
  "Religious Education (CRE/IRE/HRE)",
  "Creative Arts",
  "Physical and Health Education",
  "Social Studies",
  // Junior School (Grades 7-9)
  "Life Skills Education",
  "Computer Science",
  "Business Studies",
  "Pre-Technical Studies",
  "Visual Arts",
  "Performing Arts",
  "Sports and Physical Education",
  "Foreign Languages (French, German, Mandarin, Arabic)",
  "Kenyan Sign Language",
  "Indigenous Languages",
  // Senior School (Grades 10-12) - Pathways
  // Arts and Sports Science
  "Art and Design",
  "Music",
  "Dance",
  "Theatre and Film",
  // Social Sciences
  "History",
  "Geography",
  "Sociology",
  "Psychology",
  // STEM
  "Biology",
  "Chemistry",
  "Physics",
  "Applied Mathematics",
  "General Science",
  "Food and Nutrition",
  "Technical Drawing and Design",
  "Woodwork",
  "Metalwork",
  "Electricity",
  "Aviation Technology",
  "Building Construction",
  "Power Mechanics",
  "Leatherwork",
  "Culinary Arts",
  "Information and Communication Technology (ICT)",
];